name: cee
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pycairo
  - python=3.7.*
  - pytorch=1.0.*
  - torchvision
  - numpy
  - scipy
  - matplotlib
  - sklearn
  - pip:
    - tqdm
    - tensorboardX
    - graphviz
    - pillow